version: "3.7"

services:
  database:
    image: postgres
    container_name: database_estoque
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=estoque
      - POSTGRES_DB=estoque_livros
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: container-api
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local
